# Generated by Django 3.0.7 on 2020-07-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_relevantpages_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='default.jpg', upload_to='related_post_pics')),
            ],
        ),
        migrations.DeleteModel(
            name='RelevantPages',
        ),
    ]
